### ISSUE TITLE
plus-small icon is missing

### ISSUE THREAD

**Issue by juchom** [xt0rted/heroicons-tag-helper#207]
HeroIcons `plus-small` does not exist in `IconSymbol`, we have `plus` and `plus-circle` but the small version is missing.

**Comment by xt0rted** [comment]
That icon was added to v2.0.9 of heroicons which I haven't published a version for yet. I should be able to get that out later today.

**Comment by xt0rted** [comment]
[v2.0.9](https://github.com/xt0rted/heroicons-tag-helper/releases/tag/v2.0.9) was just published and is available on nuget. v2.0.10, v2.0.11, and v2.0.12 will be published in an hour or two.
